// TODO: Backend integration — Convex
// Table: feed_items (id, doctor_name, specialty, category, title, content, banner_gradient, avatar_gradient, likes, comments)
// Table: feed_interactions (id, user_id, feed_item_id, type: 'like'|'bookmark', created_at)
// Query: SELECT * FROM feed_items ORDER BY created_at DESC LIMIT 20
// Realtime: subscribe to feed_interactions for like counts

import { create } from "zustand";

export const FEED_ITEMS = [
  {
    id: "f1",
    doctorName: "Dr. Ramesh Gupta",
    doctorInitials: "RG",
    specialty: "Endocrinologist",
    avatarGradient: ["#0D6E4F", "#00C9A7"],
    category: "Diabetes",
    title: "5 Morning Habits That Lower Blood Sugar",
    content: "Starting your day right can dramatically affect your blood sugar levels. A 10-minute walk after breakfast reduces post-meal glucose spikes by up to 22%. Soaking methi (fenugreek) seeds overnight and drinking the water on an empty stomach improves insulin sensitivity over weeks. Skipping your morning chai with sugar is harder than it sounds — try replacing it with cinnamon water or black coffee. Eating a protein-rich breakfast (eggs, paneer, or sprouts) slows glucose absorption and keeps you full. These five habits together can reduce your HbA1c by 0.5-1% in 3 months without medication changes.",
    bannerGradient: ["#065F46", "#059669"],
    likes: 342,
    comments: 28,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "f2",
    doctorName: "Dr. Ananya Rao",
    doctorInitials: "AR",
    specialty: "Nutritionist",
    avatarGradient: ["#7C3AED", "#A78BFA"],
    category: "Nutrition",
    title: "Why You Should Never Skip Breakfast",
    content: "Skipping breakfast is one of the biggest nutrition mistakes Indians make. Your body has been fasting for 8-10 hours and needs fuel to kickstart metabolism. Studies show that breakfast skippers consume 40% more calories at lunch due to extreme hunger. For diabetic patients, skipping breakfast causes unpredictable blood sugar swings throughout the day. A good Indian breakfast — poha, idli sambhar, or vegetable upma — provides complex carbs, proteins, and fiber that sustain you for hours. Even a banana with a glass of milk is far better than nothing. Make breakfast non-negotiable.",
    bannerGradient: ["#6D28D9", "#8B5CF6"],
    likes: 287,
    comments: 41,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "f3",
    doctorName: "Dr. Vikram Patel",
    doctorInitials: "VP",
    specialty: "Psychiatrist",
    avatarGradient: ["#0369A1", "#38BDF8"],
    category: "Mental Health",
    title: "3 Breathing Exercises for Stress Relief",
    content: "Chronic stress is India's most underdiagnosed health problem. Box breathing (4-4-4-4 count) activates the parasympathetic nervous system and lowers cortisol within minutes. Pranayama — specifically Anulom Vilom (alternate nostril breathing) — has been shown to reduce blood pressure and anxiety in randomized clinical trials. The physiological sigh (double inhale through nose, long exhale through mouth) is NASA's recommended technique for rapid stress reduction. Practice any of these three for just 5 minutes daily, and you will measurably reduce perceived stress within 2 weeks. Your body already knows how to heal — give it the signal.",
    bannerGradient: ["#1E3A5F", "#2563EB"],
    likes: 198,
    comments: 19,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "f4",
    doctorName: "Dr. Priya Nair",
    doctorInitials: "PN",
    specialty: "Pathologist",
    avatarGradient: ["#B45309", "#F59E0B"],
    category: "General",
    title: "Understanding Your CBC Report in 5 Minutes",
    content: "Your Complete Blood Count report has 3 main sections. Hemoglobin tells you about anemia — normal is 13-17 g/dL for men, 12-15 for women. WBC (white blood cells) indicate infection or immunity — a count above 11,000 usually means your body is fighting something. Platelets help blood clot — below 1.5 lakh means bleeding risk, above 4 lakh could indicate inflammation. MCV (size of red cells) and MCH (hemoglobin per cell) together diagnose the TYPE of anemia — vitamin B12/folate deficiency shows large cells, iron deficiency shows small pale cells. Next time you get a CBC, you'll know exactly what to look for.",
    bannerGradient: ["#92400E", "#D97706"],
    likes: 421,
    comments: 53,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "f5",
    doctorName: "Dr. Suresh Mehta",
    doctorInitials: "SM",
    specialty: "Cardiologist",
    avatarGradient: ["#9F1239", "#F43F5E"],
    category: "Heart",
    title: "Heart-Healthy Foods in Every Indian Kitchen",
    content: "You don't need imported superfoods for a healthy heart — your kitchen already has them. Garlic reduces LDL cholesterol and prevents arterial plaque buildup when consumed raw or lightly cooked. Turmeric's curcumin is one of the most studied anti-inflammatory compounds in cardiology research. Flaxseeds (alsi) contain omega-3 fatty acids comparable to fish oil. Amla (Indian gooseberry) is richer in Vitamin C than citrus fruits and protects arterial walls. Even methi and jeera help regulate triglycerides. Add one of these to your daily diet starting today. Small consistent choices over years are what prevent heart attacks.",
    bannerGradient: ["#881337", "#E11D48"],
    likes: 376,
    comments: 34,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "f6",
    doctorName: "Dr. Kavitha Reddy",
    doctorInitials: "KR",
    specialty: "Neurologist",
    avatarGradient: ["#4338CA", "#818CF8"],
    category: "General",
    title: "When to Worry About Headaches",
    content: "Most headaches are benign — tension headaches from screen time, dehydration, or stress. However, certain headache patterns demand urgent attention. The 'thunderclap' headache — sudden, severe, 'worst of your life' — can indicate a brain bleed and requires immediate ER visit. Headaches with fever, neck stiffness, and light sensitivity suggest meningitis. A headache that progressively worsens over weeks could indicate raised intracranial pressure. Headaches on one side with visual disturbance before onset are classic migraines — manageable but worth treating properly. If your headache pattern changes significantly, always consult a neurologist rather than self-medicating with painkillers.",
    bannerGradient: ["#3730A3", "#6366F1"],
    likes: 289,
    comments: 22,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "f7",
    doctorName: "Dr. Amit Verma",
    doctorInitials: "AV",
    specialty: "Orthopedics",
    avatarGradient: ["#065F46", "#10B981"],
    category: "Nutrition",
    title: "Vitamin D Deficiency: India's Silent Epidemic",
    content: "India is a sun-rich country, yet studies show 70-90% of urban Indians are Vitamin D deficient. This is because we avoid the sun, use high-SPF sunscreen, and spend most of the day indoors. Vitamin D deficiency causes fatigue, bone pain, muscle weakness, and depression — symptoms often misdiagnosed. More alarmingly, low Vitamin D is linked to increased risk of diabetes, hypertension, and certain cancers. You cannot get therapeutic amounts from diet alone — the main source is sunlight on skin for 15-20 minutes daily between 11 AM and 1 PM (when UVB rays are present). Supplementation with 60,000 IU weekly for 8 weeks followed by maintenance doses is standard treatment. Get your Vitamin D tested — your number should be above 40 ng/mL.",
    bannerGradient: ["#064E3B", "#059669"],
    likes: 512,
    comments: 67,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "f8",
    doctorName: "Dr. Meera Sharma",
    doctorInitials: "MS",
    specialty: "Gynecologist",
    avatarGradient: ["#BE185D", "#EC4899"],
    category: "Fitness",
    title: "Safe Exercises During Pregnancy",
    content: "Exercise during pregnancy is not just safe — it's highly recommended for both mother and baby. Walking for 30 minutes daily reduces gestational diabetes risk by 40% and improves labor outcomes. Swimming is the safest full-body workout as the water supports your weight and reduces joint stress. Prenatal yoga improves flexibility, reduces back pain, and teaches breathing techniques valuable during labor. Kegel exercises (pelvic floor strengthening) prevent urinary incontinence and speed up postnatal recovery. Avoid exercises lying flat on your back after the first trimester, contact sports, and any activity with fall risk. Always clear your exercise plan with your gynecologist, especially if you have any risk factors.",
    bannerGradient: ["#9D174D", "#DB2777"],
    likes: 234,
    comments: 31,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "f9",
    doctorName: "Dr. Harish Shetty",
    doctorInitials: "HS",
    specialty: "Endocrinologist",
    avatarGradient: ["#1E40AF", "#60A5FA"],
    category: "General",
    title: "How to Read Your Thyroid Report",
    content: "Your thyroid report has three numbers: TSH, T3, and T4. TSH (thyroid stimulating hormone) from your pituitary gland is the most important — it's like the accelerator pedal. Normal TSH is 0.5-5.0 mIU/L. If TSH is high, your thyroid is underactive (hypothyroidism), and you'll feel tired, gain weight, and feel cold. If TSH is low, your thyroid is overactive (hyperthyroidism) — you'll feel anxious, lose weight, and have a fast heartbeat. Free T4 confirms the diagnosis. If your TSH is borderline (5-10), it's called subclinical hypothyroidism — often treated based on symptoms and other factors. The target TSH for patients on thyroxine is 1-3 mIU/L. Always ask for the reference range printed on your report.",
    bannerGradient: ["#1E3A8A", "#3B82F6"],
    likes: 398,
    comments: 44,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "f10",
    doctorName: "Dr. Anjali Desai",
    doctorInitials: "AD",
    specialty: "Psychiatrist",
    avatarGradient: ["#5B21B6", "#A78BFA"],
    category: "Mental Health",
    title: "Sleep Hygiene: 5 Rules for Better Sleep",
    content: "India has one of the highest rates of sleep disorders in Asia, and most people don't know they have a problem. Rule 1: Fixed wake-up time — your body clock (circadian rhythm) is anchored by when you wake up, not when you sleep. Rule 2: No screens for 1 hour before bed — blue light suppresses melatonin. Rule 3: Keep your room cool (18-22°C) — your body temperature naturally drops during sleep. Rule 4: Avoid caffeine after 2 PM — caffeine has a 6-hour half-life and is still partially active at midnight. Rule 5: Get 20 minutes of morning sunlight — this sets your body clock. If you follow these five rules for 2 weeks, I guarantee you'll feel like a different person.",
    bannerGradient: ["#4C1D95", "#7C3AED"],
    likes: 445,
    comments: 58,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "f11",
    doctorName: "Dr. Ramesh Gupta",
    doctorInitials: "RG",
    specialty: "Endocrinologist",
    avatarGradient: ["#0D6E4F", "#00C9A7"],
    category: "Diabetes",
    title: "Managing Diabetes with Indian Diet",
    content: "Indian cuisine can be completely diabetic-friendly with the right modifications. Replace white rice with millets (ragi, jowar, bajra) which have a much lower glycemic index. Curd (unsweetened) with every meal slows glucose absorption — it's a natural functional food. Dal and sabzi before rice is how traditional Indians always ate — this order reduces post-meal sugar spikes. Bitter gourd (karela) juice genuinely works for blood sugar — studies confirm it activates AMPK, the same pathway as Metformin. Replace sugar in chai with stevia or reduce gradually over 3 weeks. You don't have to give up your favorite foods — you just have to eat them smarter.",
    bannerGradient: ["#064E3B", "#10B981"],
    likes: 467,
    comments: 49,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: "f12",
    doctorName: "Dr. Suresh Mehta",
    doctorInitials: "SM",
    specialty: "Cardiologist",
    avatarGradient: ["#9F1239", "#F43F5E"],
    category: "Heart",
    title: "Blood Pressure Myths Busted",
    content: "Myth 1: 'I feel fine, so my BP must be normal.' Blood pressure has NO symptoms until it causes a heart attack or stroke — that's why it's called the silent killer. Myth 2: 'Once I start BP medication, I'll need it forever.' Not necessarily — lifestyle changes (5 kg weight loss, DASH diet, exercise) can reverse Stage 1 hypertension. Myth 3: 'Salt is the only cause of high BP.' Stress, obesity, alcohol, kidney disease, and genetics all cause hypertension. Myth 4: 'Young people don't get hypertension.' India is seeing epidemic hypertension in people in their 30s due to stress and sedentary jobs. Myth 5: 'Home BP readings are inaccurate.' A calibrated digital cuff gives readings as reliable as a doctor's office — and more representative of your true BP. Measure and know your numbers.",
    bannerGradient: ["#7F1D1D", "#DC2626"],
    likes: 329,
    comments: 37,
    isLiked: false,
    isBookmarked: false,
  },
];

export const useFeedStore = create((set) => ({
  items: FEED_ITEMS,

  toggleLike: (id) =>
    set((state) => ({
      items: state.items.map((item) =>
        item.id === id
          ? {
              ...item,
              isLiked: !item.isLiked,
              likes: item.isLiked ? item.likes - 1 : item.likes + 1,
            }
          : item
      ),
    })),

  toggleBookmark: (id) =>
    set((state) => ({
      items: state.items.map((item) =>
        item.id === id ? { ...item, isBookmarked: !item.isBookmarked } : item
      ),
    })),
}));
