"use client";

import { useRouter } from "next/navigation";
import { ChevronLeft } from "lucide-react";
import ZivikaLogo from "@/components/shared/ZivikaLogo";

const H = "Outfit, var(--font-outfit, sans-serif)";
const B = "DM Sans, var(--font-dm-sans, sans-serif)";

function Section({ title, children }) {
  return (
    <section style={{ marginBottom: 32 }}>
      <h2
        style={{
          fontFamily: H,
          fontWeight: 700,
          fontSize: "1.1rem",
          color: "#0D6E4F",
          margin: "0 0 12px",
          lineHeight: 1.3,
        }}
      >
        {title}
      </h2>
      <div
        style={{
          fontFamily: B,
          fontSize: "0.9rem",
          color: "#5A7A6E",
          lineHeight: 1.75,
        }}
      >
        {children}
      </div>
    </section>
  );
}

function Para({ children }) {
  return <p style={{ margin: "0 0 12px" }}>{children}</p>;
}

function UL({ items }) {
  return (
    <ul style={{ paddingLeft: 20, margin: "0 0 12px" }}>
      {items.map((item, i) => (
        <li key={i} style={{ marginBottom: 6 }}>
          {item}
        </li>
      ))}
    </ul>
  );
}

export default function PrivacyPage() {
  const router = useRouter();

  return (
    <div style={{ minHeight: "100dvh", background: "#F0F7F4" }}>
      {/* Sticky header */}
      <div
        style={{
          position: "sticky",
          top: 0,
          zIndex: 40,
          background: "rgba(240,247,244,0.95)",
          backdropFilter: "blur(12px)",
          padding: "14px 20px",
          display: "flex",
          alignItems: "center",
          gap: 12,
          borderBottom: "1px solid #DCE8E2",
        }}
      >
        <button
          onClick={() => router.back()}
          style={{
            background: "none",
            border: "none",
            cursor: "pointer",
            display: "flex",
            alignItems: "center",
            gap: 4,
            color: "#5A7A6E",
            fontFamily: B,
            fontSize: "0.9rem",
            padding: 0,
          }}
        >
          <ChevronLeft size={18} />
          Back
        </button>
        <ZivikaLogo size={28} showText />
      </div>

      {/* Content */}
      <div
        style={{
          maxWidth: 680,
          margin: "0 auto",
          padding: "32px 20px 80px",
        }}
      >
        <h1
          style={{
            fontFamily: H,
            fontWeight: 800,
            fontSize: "1.8rem",
            color: "#0B1F18",
            margin: "0 0 6px",
            letterSpacing: "-0.02em",
          }}
        >
          Privacy Policy
        </h1>
        <p
          style={{
            fontFamily: B,
            fontSize: "0.85rem",
            color: "#8EBAA3",
            margin: "0 0 36px",
          }}
        >
          Last updated: April 22, 2026 &nbsp;·&nbsp; Zivika Labs Pvt Ltd
        </p>

        <div
          style={{
            background: "#fff",
            borderRadius: 16,
            padding: "28px 24px",
            border: "1px solid #DCE8E2",
          }}
        >
          <Section title="1. Information We Collect">
            <Para>
              Zivika collects information you provide directly and data generated by your
              use of the service.
            </Para>
            <Para>
              <strong>Account information:</strong>
            </Para>
            <UL
              items={[
                "Email address and name (from Google OAuth or email sign-in via Clerk)",
                "Profile information: date of birth, gender, blood group, height, weight",
                "Health conditions and goals you disclose",
                "Emergency contact details",
              ]}
            />
            <Para>
              <strong>Health data you enter:</strong>
            </Para>
            <UL
              items={[
                "Medical reports and documents you scan or upload",
                "Vitals you log (blood pressure, heart rate, SpO₂, blood glucose, temperature, steps, sleep)",
                "Medications and dose logs",
                "Symptom check inputs",
                "Family member health profiles you add",
              ]}
            />
            <Para>
              <strong>Usage data (anonymised):</strong> We collect anonymised usage
              metrics (feature usage frequency, session duration) to improve the product.
              This data cannot be linked back to your identity.
            </Para>
          </Section>

          <Section title="2. How We Use Your Information">
            <UL
              items={[
                "To provide and personalise the Zivika health management service.",
                "To power AI analysis of your medical reports through Groq's API (your data is not stored by Groq for training).",
                "To send you medication reminders and health tips within the app.",
                "To improve our product using anonymised, aggregated data.",
                "We NEVER sell your personal health data to advertisers, insurers, employers, or any third party.",
              ]}
            />
          </Section>

          <Section title="3. Data Storage and Security">
            <UL
              items={[
                "Health records (images, documents) are stored using Convex File Storage with server-side encryption.",
                "All data is transmitted over HTTPS/TLS.",
                "Authentication tokens are managed by Clerk, a SOC 2 Type II certified provider.",
                "We conduct regular security reviews and monitor for anomalous access.",
                "We are actively working toward data residency in India in compliance with the DPDP Act 2023.",
              ]}
            />
          </Section>

          <Section title="4. Third-Party Services">
            <Para>
              We use the following third-party services to operate Zivika. Each has their
              own privacy policy:
            </Para>
            <UL
              items={[
                "Clerk (Authentication) — clerk.com/privacy — manages user sign-in and identity",
                "Convex (Database & Storage) — convex.dev/privacy — stores your health data",
                "Groq (AI inference) — groq.com/privacy — processes medical report images and chat messages",
                "Google (OAuth) — google.com/privacy — optional sign-in method",
                "Vercel (Hosting) — vercel.com/legal/privacy-policy — hosts the web app",
              ]}
            />
            <Para>
              We do not share your personally identifiable health data with these providers
              beyond what is necessary to operate the service.
            </Para>
          </Section>

          <Section title="5. Your Rights Under DPDP Act 2023">
            <Para>
              As a data principal under India&apos;s Digital Personal Data Protection Act
              2023, you have the following rights:
            </Para>
            <UL
              items={[
                "Right to Access: Request a copy of all personal data we hold about you.",
                "Right to Correction: Request correction of inaccurate or incomplete data.",
                "Right to Erasure: Request deletion of your account and all associated personal data.",
                "Right to Grievance Redressal: Lodge a complaint with our Data Protection Officer.",
                "Right to Nominate: Nominate a trusted person to exercise your rights in the event of death or incapacity.",
              ]}
            />
            <Para>
              To exercise any of these rights, contact:{" "}
              <a
                href="mailto:dpo@zivikalabs.com"
                style={{ color: "#0D6E4F", textDecoration: "underline" }}
              >
                dpo@zivikalabs.com
              </a>
            </Para>
          </Section>

          <Section title="6. Data Retention">
            <UL
              items={[
                "Account data is retained while your account remains active.",
                "You may request account deletion at any time.",
                "Upon deletion, your personal data will be permanently removed within 30 days.",
                "Anonymised, aggregated usage statistics may be retained indefinitely as they cannot be linked to you.",
                "We may retain limited data where required by applicable law.",
              ]}
            />
          </Section>

          <Section title="7. Children's Privacy">
            <Para>
              Zivika is intended for users aged 18 and above. We do not knowingly collect
              personal data from children under 18. If you believe we have inadvertently
              collected such data, please contact us immediately.
            </Para>
            <Para>
              Family profiles for minor dependents may be added by a parent or guardian
              who takes full responsibility for such data.
            </Para>
          </Section>

          <Section title="8. Changes to This Policy">
            <Para>
              We may update this Privacy Policy from time to time. We will notify you of
              significant changes via email or an in-app notification. Continued use of
              Zivika after changes constitutes acceptance of the updated policy.
            </Para>
          </Section>

          <Section title="9. Contact Our Data Protection Officer">
            <UL
              items={[
                "DPO Email: dpo@zivikalabs.com",
                "General Support: support@zivikalabs.com",
                "DPO: Data Protection Officer, Zivika Labs Pvt Ltd",
                "Address: Bengaluru, Karnataka, India — 560001",
              ]}
            />
          </Section>
        </div>
      </div>
    </div>
  );
}
